version: "2"
services:

  zotero-cache:
    container_name: zotero-cache 
    image: nginx:1.15.0
    ports:
     - "1969:80"
    links:
      - zotero-translation-server
    environment:
      http_proxy:  ${http_proxy}
      https_proxy: ${https_proxy}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  zotero-translation-server:
    container_name: zotero-translation-server
    image: zotero/translation-server
    environment:
      http_proxy:  ${http_proxy}
      https_proxy: ${https_proxy}
